# Generated by Django 3.0.8 on 2020-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0003_admission_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission_infonn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=200)),
                ('academic_start', models.CharField(max_length=200)),
                ('academic_end', models.CharField(max_length=200)),
                ('online_admission_application', models.CharField(max_length=200)),
                ('Admission_page_url', models.CharField(max_length=200)),
                ('Facility_to_pay_admission_online', models.CharField(max_length=200)),
                ('Admission_open', models.CharField(max_length=200)),
                ('academic_contactpersonname', models.CharField(max_length=200)),
                ('academic_contactpersonmob', models.CharField(max_length=200)),
                ('academic_contactpersonemail', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='admission_info',
        ),
    ]
