# Generated by Django 3.0.8 on 2020-08-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0004_auto_20200821_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_document_eligibility_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Admission_Details_and_Procedure', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=200)),
                ('Admission_Eligibility_Criteria', models.CharField(max_length=200)),
                ('Documents_Required_for_Admission', models.CharField(max_length=200)),
                ('Lyco_Arts', models.CharField(max_length=200)),
                ('Lyco_Science', models.CharField(max_length=200)),
                ('Lyco_Commerce', models.CharField(max_length=200)),
                ('Mcoe_Arts', models.CharField(max_length=200)),
                ('Mcoe_Science', models.CharField(max_length=200)),
                ('Mcoe_Commerce', models.CharField(max_length=200)),
            ],
        ),
    ]
