# Generated by Django 3.0.8 on 2020-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0005_admission_document_eligibility_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports_and_extra_cirrinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outdoors_sports_cricket', models.CharField(max_length=200)),
                ('outdoors_sports_Football', models.CharField(max_length=200)),
                ('outdoors_sportsHockey', models.CharField(max_length=200)),
                ('outdoors_sports_Others', models.CharField(max_length=200)),
                ('indoor_sports', models.CharField(max_length=200)),
                ('indoor_Carrom', models.CharField(max_length=200)),
                ('indoor_Tennis', models.CharField(max_length=200)),
                ('indoor_Boxing', models.CharField(max_length=200)),
                ('indoor_Others', models.CharField(max_length=200)),
                ('Kids_play_Area', models.CharField(max_length=200)),
                ('Toy_Room', models.CharField(max_length=200)),
                ('Cricket_Ground', models.CharField(max_length=200)),
                ('Swimming_pool_flash', models.CharField(max_length=200)),
                ('sports_facilities_Others', models.CharField(max_length=200)),
                ('indore_outdoor_pic', models.CharField(max_length=200)),
                ('pic_facilities', models.CharField(max_length=200)),
            ],
        ),
    ]
