# Generated by Django 3.0.8 on 2020-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0006_sports_and_extra_cirrinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards_Recognitioninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_National_Ranking', models.CharField(max_length=200)),
                ('awards_Ranking_Body', models.CharField(max_length=200)),
                ('awards_uploadimages', models.CharField(max_length=200)),
                ('awards_State_Ranking', models.CharField(max_length=200)),
                ('awards_Ranking_Body1', models.CharField(max_length=200)),
                ('awards_uploadimages1', models.CharField(max_length=200)),
                ('write_sometings_about_ranking', models.CharField(max_length=200)),
                ('write_somethings_about_sport_awards', models.CharField(max_length=200)),
                ('upload_images_and_others_Awards', models.CharField(max_length=200)),
                ('Awards_Recognitionvar', models.CharField(max_length=200)),
            ],
        ),
    ]
