# Generated by Django 3.0.8 on 2020-08-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0007_awards_recognitioninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards_recognitioninfo',
            name='Awards_Recognitionvar',
        ),
    ]
