# Generated by Django 3.0.8 on 2020-08-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0009_auto_20200825_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee_structureinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee_classwise', models.CharField(max_length=200)),
                ('admission_fee_security', models.CharField(max_length=200)),
                ('admission_fee_other', models.CharField(max_length=200)),
                ('application_register_admission_fee_classwise', models.CharField(max_length=200)),
                ('application_register_fee_for_day_school', models.CharField(max_length=200)),
                ('application_register_Transpotation_admission_fee_other', models.CharField(max_length=200)),
                ('india_Admission_Application_fee', models.CharField(max_length=200)),
                ('india_Security_deposite_fees', models.CharField(max_length=200)),
                ('india_Extra_fees', models.CharField(max_length=200)),
                ('india_Yearly_fees', models.CharField(max_length=200)),
                ('Yearly_fees_international', models.CharField(max_length=200)),
                ('Admission_Application_fee_international', models.CharField(max_length=200)),
                ('Security_deposite_fees_international', models.CharField(max_length=200)),
                ('Extra_fees_international', models.CharField(max_length=200)),
                ('Estimated_annualfees_class_Wise_international', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_Boys',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_Girls',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_boys_Boys_Girls',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_total_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_total_no_boys_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_total_no_boys_yes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
