# Generated by Django 3.0.8 on 2020-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0013_myclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='completed1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
