# Generated by Django 3.0.8 on 2020-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0014_myclass_completed1'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='completed2',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
