# Generated by Django 3.0.8 on 2020-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0015_myclass_completed2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_informationinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_information_school_name', models.CharField(max_length=200)),
                ('Basic_information_school_short_name', models.CharField(max_length=200)),
                ('Basic_information_Establishment_year', models.CharField(max_length=200)),
                ('Basic_information_tag_line_of_school', models.CharField(max_length=200)),
                ('Basic_information_url', models.CharField(max_length=200)),
                ('Basic_information_school_logo', models.CharField(max_length=200)),
                ('Basic_information_school_trusty_socity', models.CharField(max_length=200)),
                ('Basic_information_school_cover_img', models.CharField(max_length=200)),
                ('Basic_information_school_upload_brochure', models.CharField(max_length=200)),
            ],
        ),
    ]
