# Generated by Django 3.0.8 on 2020-08-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0016_basic_informationinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_informationinfo',
            old_name='Basic_information_Establishment_year',
            new_name='date',
        ),
    ]
