# Generated by Django 3.0.8 on 2020-08-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0017_auto_20200827_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_accomodationinfo',
            name='hostel_Boys',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
