# Generated by Django 3.0.8 on 2020-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fime1223', '0018_auto_20200828_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_center', models.CharField(max_length=124)),
                ('Computer_Labs', models.CharField(max_length=124)),
                ('Library', models.CharField(max_length=124)),
                ('Laboratories', models.CharField(max_length=124)),
                ('Canteen_Cafteria', models.CharField(max_length=124)),
                ('Transport_facilities', models.CharField(max_length=124)),
                ('Sports_facilities', models.CharField(max_length=124)),
                ('Medical_Facility', models.CharField(max_length=124)),
                ('Lockers', models.CharField(max_length=124)),
                ('CCTV', models.CharField(max_length=124)),
                ('Audotorium_Seminar_Hall', models.CharField(max_length=124)),
                ('Gymnasiumn', models.CharField(max_length=124)),
                ('Play_Ground', models.CharField(max_length=124)),
                ('Drinking_Water', models.CharField(max_length=124)),
                ('Music_Dance', models.CharField(max_length=124)),
                ('Stationary_Shop', models.CharField(max_length=124)),
                ('Wifi', models.CharField(max_length=124)),
                ('Car_Parking', models.CharField(max_length=124)),
                ('Bike_Cycle_Parking', models.CharField(max_length=124)),
                ('Security', models.CharField(max_length=124)),
                ('Guard', models.CharField(max_length=124)),
                ('Fire_Extinguihev', models.CharField(max_length=124)),
                ('Hygienic', models.CharField(max_length=124)),
                ('Washroom', models.CharField(max_length=124)),
                ('Hostel', models.CharField(max_length=124)),
                ('Swimming_Pool_Splash_Pool', models.CharField(max_length=124)),
                ('Others', models.CharField(max_length=124)),
                ('Facilities_Amenities_wsabi', models.CharField(max_length=124)),
                ('campusimages', models.CharField(max_length=124)),
                ('campusVideo', models.CharField(max_length=124)),
                ('campus360', models.CharField(max_length=124)),
                ('Saftey', models.CharField(max_length=124)),
                ('conteen', models.CharField(max_length=124)),
                ('Parking', models.CharField(max_length=124)),
                ('facilitiesandinfra', models.CharField(max_length=124)),
                ('youtubeurl1', models.CharField(max_length=124)),
                ('youtubeurl2', models.CharField(max_length=124)),
                ('youtubeurl3', models.CharField(max_length=124)),
                ('youtubeurl4', models.CharField(max_length=124)),
                ('txtEditor14', models.CharField(max_length=124)),
                ('txtEditor15', models.CharField(max_length=124)),
                ('txtEditor16', models.CharField(max_length=124)),
            ],
        ),
    ]
